apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: service-loadbalancing
  namespace: ingress-nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: "nginx"
spec:
  ingressClassName: nginx
  rules:
  - host: www.homepage.com
    http:
      paths:
        - path: /mainpage
          pathType: Prefix
          backend:
            service:
              name: svc-mainpage
              port:
                number: 80
        - path: /signup
          pathType: Prefix
          backend:
            service:
              name: svc-signup
              port:
                number: 80
        - path: /board
          pathType: Prefix
          backend:
            service:
              name: svc-board
              port:
                number: 80
